export const POPULAR_CAMERAS = [
  "Sony Alpha A1",
  "Sony Alpha A9 II",
  "Sony Alpha A9",
  "Sony Alpha A7R V",
  "Sony Alpha A7R IV",
  "Sony Alpha A7R III",
  "Sony Alpha A7S III",
  "Sony Alpha A7S II",
  "Sony Alpha A7 IV",
  "Sony Alpha A7 III",
  "Sony Alpha A7C",
  "Sony Alpha A7C II",
  "Sony Alpha A6700",
  "Sony Alpha A6600",
  "Sony Alpha A6400",
  "Sony FX3",
  "Sony FX30",
  "Sony ZV-E10",
  "Sony ZV-1",
  "Canon EOS R1",
  "Canon EOS R3",
  "Canon EOS R5",
  "Canon EOS R5 Mark II",
  "Canon EOS R6 Mark II",
  "Canon EOS R6",
  "Canon EOS R8",
  "Canon EOS R7",
  "Canon EOS R10",
  "Canon EOS R50",
  "Canon EOS R",
  "Canon EOS RP",
  "Canon EOS 1D X Mark III",
  "Canon EOS 5D Mark IV",
  "Canon EOS 5D Mark III",
  "Canon EOS 6D Mark II",
  "Canon EOS 90D",
  "Canon EOS 80D",
  "Canon EOS 7D Mark II",
  "Nikon Z9",
  "Nikon Z8",
  "Nikon Z7 II",
  "Nikon Z7",
  "Nikon Z6 III",
  "Nikon Z6 II",
  "Nikon Z6",
  "Nikon Zf",
  "Nikon Z5",
  "Nikon Zfc",
  "Nikon Z50",
  "Nikon D850",
  "Nikon D810",
  "Nikon D780",
  "Nikon D750",
  "Nikon D500",
  "Nikon D7500",
  "Nikon D7200",
  "Fujifilm GFX 100 II",
  "Fujifilm GFX 100S",
  "Fujifilm GFX 50S II",
  "Fujifilm X-H2S",
  "Fujifilm X-H2",
  "Fujifilm X-T5",
  "Fujifilm X-T4",
  "Fujifilm X-T3",
  "Fujifilm X-Pro3",
  "Fujifilm X-Pro2",
  "Fujifilm X-S20",
  "Fujifilm X-S10",
  "Fujifilm X-T30 II",
  "Fujifilm X100VI",
  "Fujifilm X100V",
  "Fujifilm X100F",
  "Panasonic Lumix S1H",
  "Panasonic Lumix S1R",
  "Panasonic Lumix S1",
  "Panasonic Lumix S5 IIX",
  "Panasonic Lumix S5 II",
  "Panasonic Lumix S5",
  "Panasonic Lumix GH6",
  "Panasonic Lumix GH5 II",
  "Panasonic Lumix GH5",
  "Panasonic Lumix G9 II",
  "Leica M11",
  "Leica M10",
  "Leica Q3",
  "Leica Q2",
  "Leica SL3",
  "Leica SL2",
  "Leica SL2-S",
  "OM System OM-1 Mark II",
  "OM System OM-1",
  "OM System OM-5",
  "Olympus OM-D E-M1 Mark III",
  "Olympus OM-D E-M5 Mark III",
  "Apple iPhone (iOS)",
  "Samsung Galaxy (Android)",
  "Google Pixel (Android)",
] as const;
